baseurl: "https://auto.revidian.com/"
title: "Revidian Auto"
theme: ra-theme-2022

googleAnalytics: "G-8RKF8WFYF3"

enableEmoji: true

params:
  description: ""
  tagline: "Modern Motorcycle Management - on any device"
  mailchimpURL: ""
  social:
    twitter: "RevidianAuto"
    facebook: "RevidianAuto"
    linkedin: "RevidianAuto"
    mastodon: "https://nanobyte.cafe/@RevidianAuto"
    github: "revidian-auto"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: "R/A Garage"
      url: "/garage/"
      weight: 5
    #- name: "Blog"
    #  url: "/blog/"
    #  weight: 10
    - name: "Forum"
      url: "https://forum.auto.revidian.com"
      weight: 15
    - name: "Contact Us"
      url: "/contact/"
      weight: 20
    - name: "Newsletter"
      url: "/newsletter/"
      weight: 25
  garage:
    - name: "Home"
      url: "/garage/"
      weight: -1
    - name: "Features"
      url: "/garage/features"
      weight: 5
    - name: "Pricing"
      url: "/garage/pricing/"
      weight: 10
  blog:
    - name: "Home"
      url: "/blog/"
      weight: -1
    - name: "Submit Ideas"
      url: "/blog/submit-ideas/"
      weight: 5
